DROP TABLE IF EXISTS SQL_BOOK_MAPPING;
DROP TABLE IF EXISTS SQL_BOOK;
DROP TABLE IF EXISTS BOOK_REVIEW;
DROP SCHEMA IF EXISTS sql_book;

CREATE SCHEMA sql_book;
USE sql_book;

CREATE TABLE SQL_BOOK (
	BOOK_ID INT(4) NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(50),
    AUTHOR VARCHAR(50),
    PUBLISHED_DATE DATE,
    ISBN VARCHAR(50),
    CONSTRAINT UK_TITLE UNIQUE (TITLE),
    CONSTRAINT BOOK_ID_PK PRIMARY KEY (BOOK_ID)
)ENGINE=INNODB;
ALTER TABLE SQL_BOOK AUTO_INCREMENT = 1;

CREATE TABLE BOOK_REVIEW (
	REVIEW_ID INT(4) NOT NULL AUTO_INCREMENT,
	REVIEWER_NAME VARCHAR(50),
    CONTENT VARCHAR(50),
    RATING VARCHAR(5),
    PUBLISHED_DATE DATE,
    CONSTRAINT REVIEW_ID_PK PRIMARY KEY (REVIEW_ID)
)ENGINE=INNODB;
ALTER TABLE BOOK_REVIEW AUTO_INCREMENT = 1;

CREATE TABLE SQL_BOOK_MAPPING (
	MAPPING_ID INT(4) NOT NULL AUTO_INCREMENT,
	BOOK_ID INT(4),
    REVIEW_ID INT(4),
    CONSTRAINT REVIEW_ID_PK PRIMARY KEY (MAPPING_ID),
    CONSTRAINT FK_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES SQL_BOOK(BOOK_ID),
    CONSTRAINT FK_REVIEW_ID FOREIGN KEY (REVIEW_ID) REFERENCES BOOK_REVIEW(REVIEW_ID)
)ENGINE=INNODB;
ALTER TABLE SQL_BOOK_MAPPING AUTO_INCREMENT = 1;
